package POSTAPIs;

import org.testng.Assert;
import org.testng.annotations.Test;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;

import java.io.File;

public class BookingAuthTest {
	
	//fetch the token generated by hitting this API
	@Test
	public void getBookingAuthTokenTest_WithJSON_String() {
		
		RestAssured.baseURI = "https://restful-booker.herokuapp.com";
			
	String tokenId = given()
							.contentType(ContentType.JSON)
								.body("{\n"
										+ "    \"username\" : \"admin\",\n"
										+ "    \"password\" : \"password123\"\n"
										+ "}")
								.when()
									.post("/auth")
										.then()
											.assertThat()
												.statusCode(200)
													.extract()
														.path("token");
		System.out.println(tokenId);
		Assert.assertNotNull(tokenId);
	}
	
	//----------------------------JSON File
	@Test
	public void getBookingAuthTokenTest_WithJSON_File() {
		
		RestAssured.baseURI = "https://restful-booker.herokuapp.com";
			
	String tokenId = given()
							.contentType(ContentType.JSON)
								.body(new File("./src/test/resource/data/basicauth.json"))
								.when()
									.post("/auth")
										.then()
											.assertThat()
												.statusCode(200)
													.extract()
														.path("token");
		System.out.println(tokenId);
		Assert.assertNotNull(tokenId);
	}
	
	
	//--------------------------Right way of Post call
	/*
	 * Post ---add a user --- user id = 123 ---assert(201, body)
	 * get --> get a user ---> /users/123 -- 200 --- userId = 123
	 * 
	 * Should be one test case only
	 */
	
	@Test
	public void addUserTest() {
		
		RestAssured.baseURI = "https://gorest.co.in";
		
		//1. Add user --POST
	int userId = given().log().all()
					.contentType(ContentType.JSON)
					.body(new File("./src/test/resource/data/addUser.json"))
					.header("Authorization", "Bearer 55b2c799844a831c6401e7b4178327f0a3c5c12f66359af247c473a18cd5fe76").
				 when()
				 	.post("/public/v2/users/").
				 then().log().all()
				 	.assertThat()
				 	.statusCode(201)
				 	.and()
				 	.body("name", equalTo("Ashu"))
				 	.extract()
				 		.path("id");
				
		System.out.println("User id: " + userId);		
		
		//2. Get the same user and verify it : GET 
		given()
		.header("Authorization", "Bearer 55b2c799844a831c6401e7b4178327f0a3c5c12f66359af247c473a18cd5fe76")
			.when().log().all()
				.get("/public/v2/users/" + userId) //append user id here
					.then()
						.assertThat()
							.statusCode(200)
								.and()
									.body("id", equalTo(userId));
	}
	

}
